name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # This triggers the workflow on push to the main branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Use the Node.js version you are using

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build  # Make sure this builds your project

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # This points to your build directory
        publish_branch: gh-pages  # This is where your site is published
